// File explaining the post installation process ran via script command in package.json

const { color, getTimestamp } = require('../utils/loggingEffects.js');
const config = require('../config.js')

console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_PROCESS] Welcome to the post installation process for ${config.botName}!${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_PROCESS] All dependencies have been installed successfully! Please continue with the installation process following the instructions found below${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_PROCESS] If you have any questions or need help, please visit our Discord server at ${config.botServerInvite}${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_PROCESS] ================================================================================================${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_PROCESS]  ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗          ██████╗ ██╗   ██╗██╗██████╗ ███████╗${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_PROCESS]  ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║         ██╔════╝ ██║   ██║██║██╔══██╗██╔════╝${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_PROCESS]  ██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║         ██║  ███╗██║   ██║██║██║  ██║█████╗  ${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_PROCESS]  ██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║         ██║   ██║██║   ██║██║██║  ██║██╔══╝  ${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_PROCESS]  ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗    ╚██████╔╝╚██████╔╝██║██████╔╝███████╗${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_PROCESS]  ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝     ╚═════╝  ╚═════╝ ╚═╝╚═════╝ ╚══════╝${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_PROCESS] ================================================================================================${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[1.]${color.reset}${color.pink} Once you've got your dependencies installed, which you should have if your reading this, edit the file named 'example.env' to be called '.env'.${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[2.]${color.reset}${color.pink} Once you've edited the 'example.env' file to be called '.env', you'll then want to go through and fill out the values in the file. \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[2.] [TOKEN]${color.reset}${color.pink} 'token' is your bot token, which you can get from the Discord Developer Portal. \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[2.] [CLIENTID]${color.reset}${color.pink} 'clientid' is your bot's ID which you can get by right clicking the bot and clicking 'Copy User ID'. \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[2.] [GUILDID]${color.reset}${color.pink} 'guildid' is the ID of any server that your bot may be in, it can quite literally be any server ID though. \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[2.] [DEVID]${color.reset}${color.pink} 'devid' is your Discord ID, which you can get by right clicking your name and clicking 'Copy User ID'. \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[2.] [MONGODB]${color.reset}${color.pink} 'mongodb' is the URL to your MongoDB database, which you can get by creating a cluster on MongoDB Atlas. \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[2.] [MOVIETRACKERAPI]${color.reset}${color.pink} 'movietrackerapi' is for the Movie Tracker API, which you can get by signing up at https://www.themoviedb.org/. \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[2.] [RAPIDAPIKEY]${color.reset}${color.pink} 'rapidapikey' is for the RapidAPI, which you can get by signing up at https://rapidapi.com/.${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[3.]${color.reset}${color.pink} When you've finished editing the '.env' file, you can move across to editing the 'config.js' file which holds lots of the configuration \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[3.] [CONTINUED]${color.reset}${color.pink} for the bot. You can change this to your liking, however, DO NOT change any of the naming conventions else it will break some of the \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[3.] [CONTINUED]${color.reset}${color.pink} commands and will require them to be fixed by updating the name.${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[4.]${color.reset}${color.pink} Once you've finished editing the '.env' and 'config.js' files, you can then run the bot by typing 'npm run start' in the terminal. \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[4.] [CONTINUED]${color.reset}${color.pink} This will start the bot up and you should see the bot come online in the Discord client.${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[5.]${color.reset}${color.pink} For any errors you get with the start up, be sure to leave them here - https://discordapp.com/channels/970775928596746290/1254876091810582632 \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[5.] [CONTINUED]${color.reset}${color.pink} or create a post in the js-help channel https://discordapp.com/channels/970775928596746290/1168247660944302090 and we'll be sure \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[5.] [CONTINUED]${color.reset}${color.pink} to help you out!${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[6.]${color.reset}${color.pink} Enjoy the bot and have fun with it!${color.reset}`);
console.log(`${color.pink}[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[NOTE]${color.reset}${color.pink} *Note: The file names '.development.example.env', this is used as a development environment file and loads a development bot \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[NOTE] [CONTINUED]${color.reset}${color.pink} token, client ID, guild ID, and MongoDB URL. This is used for testing purposes and should not be used in a production environment. \n[${getTimestamp()}] [INSTALLATION_GUIDE] ${color.reset}${color.yellow}[NOTE] [CONTINUED]${color.reset}${color.pink} You can just leave this file however and ignore it.${color.reset}`);