import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Collection, PermissionsBitField } from "discord.js";
import { format, resolveConfig } from "prettier";
import { ALL_CATEGORIES, categoryEmoji, categoryLabel, HIDDEN_CATEGORIES } from "@config/categories";
import { type TestifyClient } from "@core/client";
import { type Command, subcommandsOf } from "@core/command";
import { loadEverything } from "@core/loader";
import { createLogger } from "@core/logger";
import { humanisePermission } from "@lib/format/format.util";

/** Writes docs/commands.md from the commands on disk, so the list cannot go stale. */

const client = {
	commands: new Collection<string, Command>(),
	aliases: new Collection<string, string>(),
	buttons: new Collection(),
	messageHandlers: [],
	logger: createLogger("fatal", false),
	on: () => undefined,
	once: () => undefined,
} as unknown as TestifyClient;

loadEverything(client);

const commands = [...client.commands.values()];
const shown = ALL_CATEGORIES.filter((category) => !HIDDEN_CATEGORIES.includes(category));
const listed = commands.filter((command) => shown.includes(command.category));
const subcommandCount = listed.reduce((total, command) => total + subcommandsOf(command).length, 0);
const aliasesOf = (command: Command): string[] => [
	...(command.aliases ?? []),
	...subcommandsOf(command).flatMap((sub) => sub.aliases ?? []),
];
const aliasCount = listed.reduce((total, command) => total + aliasesOf(command).length, 0);

/** A shields.io badge whose figure is counted here, so it cannot drift from the code. */
const badge = (label: string, value: number, colour: string): string =>
	`![${label}: ${value}](https://img.shields.io/badge/${encodeURIComponent(label)}-${value}-${colour}?style=for-the-badge)`;

/** Every permission a member needs for the command or any of its subcommands, in words. */
function needs(command: Command): string {
	const flags = [command.permissions ?? [], ...subcommandsOf(command).map((sub) => sub.permissions ?? [])].flat();
	const names = [...new Set(new PermissionsBitField(flags).toArray())].map((name) => {
		const words = humanisePermission(name);
		return words.charAt(0).toUpperCase() + words.slice(1);
	});
	return names.length === 0 ? "—" : names.join(", ");
}

/** GitHub's heading anchor: symbols go, a variation selector and the space after an emoji stay. */
const anchor = (heading: string): string =>
	heading
		.toLowerCase()
		.replace(/[^\p{L}\p{M}\p{N}\s_-]/gu, "")
		.replace(/\s/g, "-");

const lines: string[] = [
	'<div align="center">',
	"",
	"# 📋 Commands",
	"",
	"**Every command works as `/name` and as `t?name` — one implementation, two ways in.**",
	"",
	[
		badge("commands", listed.length, "8b5cf6"),
		badge("subcommands", subcommandCount, "0ea5e9"),
		badge("prefix aliases", aliasCount, "16a34a"),
	].join(" "),
	"",
	"</div>",
	"",
	"> [!NOTE]",
	"> This file is generated by `npm run docs:commands` from the commands themselves — edit the commands, not this.",
	"> Owner-only commands are left out. Run `/help` in Discord for the browsable version.",
	"",
	"| Category | Commands | Subcommands |",
	"| --- | :---: | :---: |",
];

for (const category of shown) {
	const inCategory = listed.filter((command) => command.category === category);
	if (inCategory.length === 0) continue;
	const heading = `${categoryEmoji(category)} ${categoryLabel(category)}`;
	const subs = inCategory.reduce((total, command) => total + subcommandsOf(command).length, 0);
	lines.push(`| [${heading}](#${anchor(heading)}) | ${inCategory.length} | ${subs} |`);
}

lines.push("");

for (const category of shown) {
	const inCategory = listed
		.filter((command) => command.category === category)
		.sort((a, b) => a.name.localeCompare(b.name));
	if (inCategory.length === 0) continue;

	lines.push(`## ${categoryEmoji(category)} ${categoryLabel(category)}`, "");
	lines.push("| Command | Description | Subcommands | Prefix aliases | Needs |", "| --- | --- | --- | --- | --- |");

	for (const command of inCategory) {
		const subcommands = subcommandsOf(command)
			.map((sub) => `\`${sub.name}\``)
			.join(", ");
		const aliases = aliasesOf(command)
			.map((alias) => `\`t?${alias}\``)
			.join(", ");

		lines.push(
			`| \`/${command.name}\` | ${command.description} | ${subcommands || "—"} | ${aliases || "—"} | ${needs(command)} |`,
		);
	}

	lines.push("");
}

async function main(): Promise<void> {
	const target = resolve(process.cwd(), "docs", "commands.md");
	// Formatted here, so the file passes `format:check` the moment it is written.
	const formatted = await format(`${lines.join("\n")}\n`, { ...(await resolveConfig(target)), parser: "markdown" });
	writeFileSync(target, formatted, "utf8");
	console.log(`Wrote docs/commands.md with ${listed.length} commands.`);
}

main().catch((error: unknown) => {
	console.error(error);
	process.exit(1);
});
