import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Collection } from "discord.js";
import { ALL_CATEGORIES, categoryEmoji, categoryLabel, HIDDEN_CATEGORIES } from "@config/categories";
import { type TestifyClient } from "@core/client";
import { type Command, subcommandsOf } from "@core/command";
import { loadEverything } from "@core/loader";
import { createLogger } from "@core/logger";

/** Writes COMMANDS.md from the commands on disk, so the list cannot go stale. */

const client = {
	commands: new Collection<string, Command>(),
	aliases: new Collection<string, string>(),
	buttons: new Collection(),
	messageHandlers: [],
	logger: createLogger("fatal", false),
	on: () => undefined,
	once: () => undefined,
} as unknown as TestifyClient;

loadEverything(client);

const commands = [...client.commands.values()];
const lines: string[] = [
	"# Commands",
	"",
	`${commands.length} commands. Every one works as \`/name\` and as \`t?name\`.`,
	"",
	"This file is generated by `npm run docs:commands` — edit the commands, not this.",
	"",
];

for (const category of ALL_CATEGORIES) {
	if (HIDDEN_CATEGORIES.includes(category)) continue;

	const inCategory = commands
		.filter((command) => command.category === category)
		.sort((a, b) => a.name.localeCompare(b.name));
	if (inCategory.length === 0) continue;

	lines.push(`## ${categoryEmoji(category)} ${categoryLabel(category)}`, "");
	lines.push("| Command | Description | Subcommands | Prefix aliases |", "| --- | --- | --- | --- |");

	for (const command of inCategory) {
		const subcommands = subcommandsOf(command)
			.map((sub) => `\`${sub.name}\``)
			.join(", ");
		const aliases = [...(command.aliases ?? []), ...subcommandsOf(command).flatMap((sub) => sub.aliases ?? [])]
			.map((alias) => `\`t?${alias}\``)
			.join(", ");

		lines.push(`| \`/${command.name}\` | ${command.description} | ${subcommands || "—"} | ${aliases || "—"} |`);
	}

	lines.push("");
}

writeFileSync(resolve(process.cwd(), "COMMANDS.md"), `${lines.join("\n")}\n`, "utf8");
console.log(`Wrote COMMANDS.md with ${commands.length} commands.`);
