import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Collection } from "discord.js";
import {
	ALL_CATEGORIES,
	type Category,
	categoryEmoji,
	categoryLabel,
	HIDDEN_CATEGORIES,
} from "../src/config/categories";
import { DEFAULT_PREFIX } from "../src/config/constants";
import { type TestifyClient } from "../src/core/client";
import { allSubcommands, type SharedCommand } from "../src/core/command";
import { createLogger } from "../src/core/logger";
import { MessagePipeline } from "../src/core/messagePipeline";
import { registerAll } from "../src/core/registry";

/**
 * Generates COMMANDS.md from the live registry, so the published command list
 * cannot drift from the code the way the hand-written tables did.
 */

const logger = createLogger({ level: "fatal", pretty: false });

const client = {
	commands: new Collection<string, SharedCommand>(),
	aliases: new Collection<string, string>(),
	components: new Collection(),
	logger,
	on: () => undefined,
	once: () => undefined,
} as unknown as TestifyClient;

registerAll(client, new MessagePipeline(logger), logger);

const commands = [...client.commands.values()].filter((command) => !HIDDEN_CATEGORIES.includes(command.category));

function surfaces(command: SharedCommand): string {
	return command.surfaces
		.map((surface) => (surface === "slash" ? `\`/${command.name}\`` : `\`${DEFAULT_PREFIX}${command.name}\``))
		.join("<br>");
}

function describe(command: SharedCommand): string {
	const subs = allSubcommands(command);
	const aliases = command.aliases ?? [];

	return [
		command.description,
		subs.length > 0 ? `<br>**Subcommands:** ${subs.map((sub) => `\`${sub.name}\``).join(", ")}` : "",
		aliases.length > 0 ? `<br>**Aliases:** ${aliases.map((alias) => `\`${alias}\``).join(", ")}` : "",
	]
		.filter(Boolean)
		.join("");
}

const lines: string[] = [
	"<!-- Generated by `npx tsx scripts/generateCommandDocs.ts`. Do not edit by hand. -->",
	"",
	"# Commands",
	"",
	`${commands.length} commands across ${ALL_CATEGORIES.filter((category) => commands.some((command) => command.category === category)).length} categories.`,
	"",
	"Slash commands are shown with `/`; prefix commands use the server's configured prefix",
	`(\`${DEFAULT_PREFIX}\` by default).`,
	"",
	"## Contents",
	"",
];

const populated = ALL_CATEGORIES.filter((category) => commands.some((command) => command.category === category));

for (const category of populated) {
	const count = commands.filter((command) => command.category === category).length;
	lines.push(`- [${categoryEmoji[category]} ${categoryLabel[category]}](#${slug(category)}) — ${count}`);
}

for (const category of populated) {
	lines.push("", `## ${categoryEmoji[category]} ${categoryLabel[category]}`, "");
	lines.push("| Command | Usage | Description |", "|---|---|---|");

	for (const command of commands
		.filter((entry) => entry.category === category)
		.sort((a, b) => a.name.localeCompare(b.name))) {
		lines.push(`| \`${command.name}\` | ${surfaces(command)} | ${describe(command)} |`);
	}
}

lines.push("");

function slug(category: Category): string {
	return `${categoryEmoji[category]}-${categoryLabel[category]}`
		.toLowerCase()
		.replace(/[^a-z0-9\s-]/g, "")
		.trim()
		.replace(/\s+/g, "-");
}

const target = resolve(process.cwd(), "COMMANDS.md");
writeFileSync(target, lines.join("\n"), "utf8");

console.log(`Wrote ${target} with ${commands.length} commands.`);
