import { existsSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { resolve } from "node:path";
import prompts from "prompts";

/**
 * Generates a `.env` from one description of the environment, so the example
 * file and the code cannot drift apart. The previous generator wrote the four
 * webhook keys all-lowercase while the code read them camelCase, which silently
 * disabled slash logging, prefix logging, bug reports and suggestions for
 * everyone who followed the documented setup.
 */

interface EnvField {
	key: string;
	message: string;
	required: boolean;
	generate?: () => string;
	hint?: string;
}

const FIELDS: EnvField[] = [
	{ key: "DISCORD_TOKEN", message: "Bot token", required: true, hint: "Discord Developer Portal → Bot → Token" },
	{ key: "DISCORD_CLIENT_ID", message: "Application (client) ID", required: true },
	{ key: "DISCORD_OWNER_IDS", message: "Owner user IDs (comma separated)", required: true },
	{ key: "MONGODB_URI", message: "MongoDB connection string", required: true },
	{ key: "DISCORD_DEV_GUILD_ID", message: "Development guild ID (instant command updates)", required: false },
	{ key: "LOG_LEVEL", message: "Log level (trace/debug/info/warn/error/fatal)", required: false },
	{ key: "CHANNEL_GUILD_JOIN_LOG", message: "Channel ID for guild-join logs", required: false },
	{ key: "CHANNEL_GUILD_LEAVE_LOG", message: "Channel ID for guild-leave logs", required: false },
	{ key: "CHANNEL_COMMAND_ERROR_LOG", message: "Channel ID for command errors", required: false },
	{ key: "CHANNEL_EVAL_LOG", message: "Channel ID for eval logs", required: false },
	{ key: "CHANNEL_DM_LOG", message: "Channel ID for direct-message logs", required: false },
	{ key: "WEBHOOK_SLASH_LOGGING", message: "Webhook URL for slash command logging", required: false },
	{ key: "WEBHOOK_PREFIX_LOGGING", message: "Webhook URL for prefix command logging", required: false },
	{ key: "WEBHOOK_BUG_REPORTS", message: "Webhook URL for bug reports", required: false },
	{ key: "WEBHOOK_SUGGESTIONS", message: "Webhook URL for suggestions", required: false },
	{ key: "WEBHOOK_CONSOLE_LOGGING", message: "Webhook URL mirroring warnings and errors", required: false },
	{ key: "TMDB_API_KEY", message: "TMDB API key (film lookups)", required: false },
	{ key: "RAPID_API_KEY", message: "RapidAPI key", required: false },
	{ key: "CLASH_ROYALE_API_KEY", message: "Clash Royale API key", required: false },
	{ key: "SPOTIFY_CLIENT_ID", message: "Spotify client ID", required: false },
	{ key: "SPOTIFY_CLIENT_SECRET", message: "Spotify client secret", required: false },
	{ key: "SPOTIFY_REDIRECT_URI", message: "Spotify redirect URI", required: false },
	{ key: "OAUTH_PORT", message: "Port for the OAuth callback server", required: false },
	{
		key: "OAUTH_STATE_SECRET",
		message: "OAuth state signing secret (leave blank to generate)",
		required: false,
		generate: () => randomBytes(32).toString("hex"),
	},
	{
		key: "TOKEN_ENCRYPTION_KEY",
		message: "32-byte hex key for encrypting third-party tokens (leave blank to generate)",
		required: false,
		generate: () => randomBytes(32).toString("hex"),
	},
	{ key: "NGROK_AUTH_TOKEN", message: "ngrok auth token", required: false },
];

/** Values containing anything shell-sensitive are quoted so the file stays parseable. */
function serialise(key: string, value: string): string {
	if (value.length === 0) return `${key}=`;
	return /[\s#"'$`\\]/.test(value) ? `${key}="${value.replace(/(["\\])/g, "\\$1")}"` : `${key}=${value}`;
}

export function renderExample(): string {
	const lines = ["# Generated by `npm run env:setup`. Every key here is read by src/config/env.ts.", ""];

	for (const field of FIELDS) {
		lines.push(`# ${field.message}${field.required ? " (required)" : ""}`);
		if (field.hint !== undefined) lines.push(`# ${field.hint}`);
		lines.push(`${field.key}=`, "");
	}

	return lines.join("\n");
}

async function main(): Promise<void> {
	const development = process.argv.includes("--development");
	const target = resolve(process.cwd(), development ? ".env.development" : ".env");

	if (existsSync(target)) {
		const { overwrite } = await prompts({
			type: "confirm",
			name: "overwrite",
			message: `${target} already exists. Overwrite it?`,
			initial: false,
		});
		if (overwrite !== true) {
			console.log("Cancelled.");
			return;
		}
	}

	const lines: string[] = [];

	for (const field of FIELDS) {
		const { value } = await prompts({
			type: "text",
			name: "value",
			message: `${field.message}${field.required ? " *" : ""}`,
		});

		const resolved = typeof value === "string" && value.length > 0 ? value : (field.generate?.() ?? "");

		if (field.required && resolved.length === 0) {
			console.error(`\n${field.key} is required. Nothing was written.`);
			process.exitCode = 1;
			return;
		}

		lines.push(serialise(field.key, resolved));
	}

	if (development) lines.unshift("NODE_ENV=development");

	writeFileSync(target, `${lines.join("\n")}\n`, "utf8");
	writeFileSync(resolve(process.cwd(), ".env.example"), renderExample(), "utf8");

	console.log(`\nWrote ${target} and refreshed .env.example.`);
}

if (require.main === module) {
	main().catch((error: unknown) => {
		console.error(error);
		process.exitCode = 1;
	});
}
